### ISSUE TITLE
Bug when validate the timestamp in webhooks

### ISSUE THREAD

**Issue by alex-banknovo** [lithic-com/lithic-go#2]
The header `webhook-timestamp` arrives in `Unix` format, not `Unixmilli`, but [this](https://github.com/lithic-com/lithic-go/blob/b6729aaced38a0ee2130559afdcc26647002bc2a/services/webhooks.go#L54-L59) validation is in Milliseconds, then I have an error in the sandbox when using the `VerifySignature` method.

**Comment by rattrayalex** [comment]
Thank you! We'll get this patched up shortly.

**Comment by rattrayalex** [comment]
Released as `v0.1.1` – thank you for reporting @alex-banknovo!
